name:                llvm-strong
version:             0.1.0.0
github:              "CRogers/llvm-strong"
license:             BSD3
author:              "Callum Rogers"
maintainer:          "message.me@github.com"
copyright:           "Callum Rogers 2017"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/CRogers/llvm-strong#readme>

dependencies:
- base >= 4.7 && < 5
- llvm-hs
- llvm-hs-pure
- llvm-hs-pretty
- text

library:
  source-dirs: src

executables:
  llvm-strong-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-strong

tests:
  llvm-strong-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-strong
